services:

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped

  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    
